-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})

hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1080@144",
    position = "0x0",
    scale    = 1,
})

-- monitor = DP-1,2560x1440@240,1920x0,1, bitdepth, 10, cm, hdr, sdrbrightness, 1.4, sdrsaturation, 1 

hl.monitor({
    output   = "DP-1",
    mode     = "2560x1440@240",
    position = "1920x0",
    scale    = 1,
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@75",
    position = "0x0",
    scale    = 1,
})

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

local terminal = "ghostty"

local fileManager = "nautilus"

local menu = "vicinae toggle"

local app = "pkill -SIGUSR1 waybar && nwg-drawer -pblock hyprlock && pkill -SIGUSR1 waybar"

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("QT_IM_MODULE", "fcitx")

hl.env("XMODIFIERS", "@im=fcitx")

hl.env("SDL_IM_MODULE", "fcitx")

hl.env("GTK_THEME", "Colloid-Purple-Dark-Catppuccin")

hl.config({
    input = {
        kb_layout = "it",
        follow_mouse = 1,
        touchpad = {
            natural_scroll = false,
            scroll_factor = 0.2,
        },
        sensitivity = -0.1,
    },
})

hl.config({
    general = {
        gaps_in = 10,
        gaps_out = 10,
        border_size = 2,
        layout = "dwindle",
        allow_tearing = false,
        col = {
            active_border = "rgb(cba6f7)",
            inactive_border = "rgba(595959aa)",
        },
    },
})

hl.config({
    decoration = {
        rounding = 10,
        blur = {
            enabled = true,
            size = 5,
            --noise = 0
            --brightness = 3
            passes = 4,
            new_optimizations = true,
            xray = false,
            ignore_opacity = true,
            --vibrancy = 0.3
            --vibrancy_darkness = 0.3
        },
        shadow = {
            enabled = false,
            range = 10,
            render_power = 10,
            color = "rgba(cba6feee)",
            color_inactive = "rgba(181825ee)",
        },
        active_opacity = 0.97,
        inactive_opacity = 0.95,
    },
})

hl.config({
    animations = {
        enabled = true,
    },
})
hl.curve("myBezier", {
    type = "bezier",
    points = { { 0.05, 0.9 }, { 0.1, 1.05 } },
})
hl.animation({ leaf = "windows", enabled = true, speed = 7, bezier = "myBezier" })
-- hl.animation({ leaf = "windowsOut", enabled = true, speed = 7, style = "popin 80%" })
-- hl.animation({ leaf = "border", enabled = true, speed = 10 })
-- hl.animation({ leaf = "borderangle", enabled = true, speed = 8 })
-- hl.animation({ leaf = "fade", enabled = true, speed = 7 })
-- hl.animation({ leaf = "workspaces", enabled = true, speed = 5, style = "slidehori" })

-- hl.config({
--     dwindle = {
--         pseudotile = true,
--         preserve_split = true,
--     },
-- })

hl.gesture({
    ["fingers"] = 3,
    ["direction"] = "vertical",
    ["action"] = "workspace",
})

hl.config({
    misc = {
        force_default_wallpaper = -1,
        -- Set to 0 to disable the anime mascot wallpapers
    },
})

local mainMod = "SUPER"

hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("ghostty"))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "M", hl.dsp.exec_cmd("wlogout"))

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("nautilus"))

hl.bind(mainMod .. " + " .. "S", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("vicinae toggle"))

hl.bind(mainMod .. " + " .. "A", hl.dsp.exec_cmd("pkill -SIGUSR1 waybar && nwg-drawer -pblock hyprlock && pkill -SIGUSR1 waybar"))

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

-- dwindle

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

hl.bind("SUPER" .. " + " .. "W", hl.dsp.exec_cmd("pkill -SIGUSR1 waybar"))

-- Example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "B", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "B", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "H", hl.dsp.focus({ workspace = "r-1" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.focus({ workspace = "r+1" }))

hl.bind(mainMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

-- hl.window_rule({
--     name  = "opacity_0_80_0_80",
--     match = {
--         class = "(obsidian)",
--     },
--     opacity = { 0.80, 0.80 },
-- })

hl.window_rule({
    name  = "float",
    match = {
        class = "(vicinae)",
    },
    float = true,
})

-- hl.window_rule({
--     name  = "opacity_0_80_0_80",
--     match = {
--         class = "(anki)",
--     },
--     opacity = { 0.80, 0.80 },
-- })
--
-- hl.window_rule({
--     name  = "opacity_0_80_0_80",
--     match = {
--         title = "(Visual Studio Code)",
--     },
--     opacity = { 0.80, 0.80 },
-- })
--
-- hl.window_rule({
--     name  = "opacity_0_80_0_80",
--     match = {
--         title = "(IDX)",
--     },
--     opacity = { 0.80, 0.80 },
-- })



hl.bind("CTRL" .. " + " .. "Print", hl.dsp.exec_cmd("grimblast edit area"))

hl.bind("SUPER" .. " + " .. "Print", hl.dsp.exec_cmd("grimblast edit area"))

hl.bind("ALT" .. " + " .. "Print", hl.dsp.exec_cmd("grimblast edit area"))

hl.bind("Print", hl.dsp.exec_cmd("grimblast copysave area"))

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("swayosd-client --brightness +5"))

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("swayosd-client --brightness -5"))

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("swayosd-client --output-volume toggle-mute"))

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("swayosd-client --input-volume toggle-mute"))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --output-volume raise"))

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --output-volume lower"))

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("swayosd-client --playerctl play-pause"))

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("swayosd-client --playerctl next"))

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("swayosd-client --playerctl prev"))

hl.bind("CTRL + SUPER" .. " + " .. "M", hl.dsp.exec_cmd("hyprlock"))

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("fcitx5")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("waybar")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("swaync")
    hl.exec_cmd("hyprctl setcursor catppuccin-mocha-mauve-cursors 24")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-theme \"catppuccin-mocha-mauve-cursors\"")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("otd-daemon")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("nextcloud")
    hl.exec_cmd("discord --start-minimized")
    hl.exec_cmd("steam -silent")
    hl.exec_cmd("swayosd-server")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/lib/xdg-desktop-portal-hyprland")
    hl.exec_cmd("vicinae server")
end)

-- Exec (run every reload)
hl.on("config.reloaded", function()
    hl.exec_cmd("hyprpaper")
end)
